### ISSUE TITLE
bx iam service-ids command does not list all service id's -- lists a maximum of 20

### ISSUE THREAD

**Issue by hjv333** [IBM-Bluemix/bluemix-cli-release#10]
bx iam service-ids command does not list all service id's.

Maximum of 20 service-ids are listed, even though the bluemix account has more than 20 service-id's.

$ bx --version
bx version 0.6.1+724c406b-2017-10-09T03:12:39+00:00

**Comment by boyang9527** [comment]
thanks for reporting the issue, will check and verify

**Comment by archerzz** [comment]
We don't do pagination when listing all service IDs. This should be fixed in 0.6.2. Thanks for reporting.
