### ISSUE TITLE
bx ic init fails

### ISSUE THREAD

**Issue by bideshd** [IBM-Bluemix/bluemix-cli-release#4]
bx ic init fails with below error. Bluemix region is US South.

PS C:\windows\system32> bx ic init
Deleting old configuration file...
Generating client certificates for IBM Containers...
runtime error: invalid memory address or nil pointer dereference

**Comment by JunliWang** [comment]
this problem should be fixed by installing IBM-Containers version 1.0.1028
```
$bx plugin install IBM-Containers -r Bluemix
```
```
$ bx plugin list
Listing installed plug-ins...

Plugin Name       Version   
IBM-Containers    1.0.1028   
````
