### ISSUE TITLE
I'm try to login with bluemix cli, but always get the following error

### ISSUE THREAD

**Issue by wangzhidong** [IBM-Bluemix/bluemix-cli-release#6]
bluemix login  -a https://api.eu-gb.bluemix.net --sso --apikey 
Get https://api.eu-gb.bluemix.net/v2/info: dial tcp 5.10.124.140:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by boyang9527** [comment]
The message indicated you were not able to connect 5.10.124.140 which is the IP address of api.eu-gb.bluemix.net
please check your network settings to see whether you can access url  https://api.eu-gb.bluemix.net/v2/info

**Comment by boyang9527** [comment]
by the way,  use 'bluemix login --sso' to login with one time passcode, use 'blueix login --apikey key or @keyfile' to login with api key or apikey file.
