### ISSUE TITLE
I'm getting an "unknown version" error on mac osx download

### ISSUE THREAD

**Issue by Laskewitz** [IBM-Bluemix/bluemix-cli-release#8]
Hi,

I'm getting an "unknown version" error when I want to download the newest mac osx version of the Bluemix CLI through this page:
https://github.com/IBM-Bluemix/bluemix-cli-release/releases 

Kind regards,
Daniel

**Comment by boyang9527** [comment]
I guess you just hit the refresh window of the new release... checked the links, they are good.  Please reopen this issue if still have it.
